### ISSUE TITLE
Thread exception

### ISSUE THREAD

**Issue by fisher2099** [nlsdfnbch/Pysher#18] opened 2018-04-09 05:45 UTC
Hi，
when  received error 4xxx， the connection performs reconnect, but it seems the websocket thread exception raised because of socket re-open, and then the thread exits. You can see the following 'ping' get no 'pong' respond(2018-04-08 22:32:26,969 ping）, and can not reconnect any more unless restart the program. It happens one time in several hours.
Here is the log information from connection.py:

2018-04-08 22:30:26,962 - connection.py[line:278] - ERROR: Connection: Received error 4201
2018-04-08 22:30:26,963 - connection.py[line:88] - INFO: start Reconnect:0
2018-04-08 22:30:26,963 - connection.py[line:92] - INFO: Connection: Reconnect in 0
2018-04-08 22:30:26,963 - connection.py[line:97] - INFO: socket.close() start
close status: 4201
2018-04-08 22:30:26,964 - connection.py[line:99] - INFO: socket.close() ok
2018-04-08 22:30:26,971 - connection.py[line:125] - INFO: Attempting to connect again in 0 seconds.
2018-04-08 22:30:26,971 - connection.py[line:133] - INFO: self.socket.run_forever start
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/work/dataapi/python/pysher/connection.py", line 102, in run
    self._connect()
  File "/home/ubuntu/work/dataapi/python/pysher/connection.py", line 134, in _connect
    self.socket.run_forever(**self.socket_kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.4/lib/python3.6/site-packages/websocket/_app.py", line 203, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened

2018-04-08 22:32:26,969 - connection.py[line:221] - INFO: Connection: ping to pusher
2018-04-08 22:32:26,969 - connection.py[line:225] - ERROR: Failed send ping: socket is already closed.
2018-04-08 22:35:31,972 - connection.py[line:298] - INFO: _connection_timed_out:Did not receive any data in time.  Reconnecting.
2018-04-08 22:35:31,972 - connection.py[line:88] - INFO: start Reconnect:None
2018-04-08 22:35:31,972 - connection.py[line:92] - INFO: Connection: Reconnect in 10
2018-04-08 22:35:31,972 - connection.py[line:97] - INFO: socket.close() start
2018-04-08 22:35:31,972 - connection.py[line:99] - INFO: socket.close() ok_

**Comment by TraderVK** [comment] 2018-04-26 18:33
Having exactly the same issue here. Have you found any solution?

**Comment by deepbrook** [comment] 2018-05-01 05:50
I haven't found the time to look into this yet, unfortunately. Anyone else ?

**Comment by berentn** [comment] 2018-07-31 19:49
I also encountered this bug. It seems to happen in the connection class when it executes `_connect(self)` after handling an error and it tries to reconnect. My theory is that the thread fails because  `self.socket.run_forever(**self.socket_kwargs)` gets executed for a second time in the `while self.needs_reconnect and not self.disconnect_called:` loop ( because `self.needs_reconnect` is set to True by `calling reconnect(..)` )

I'll take a look into it at a later moment because I need to familiarize myself a bit more with the code to understand how to fix it properly (and find out if that is indeed the cause of the bug)

**Comment by xmurobi** [comment] 2018-08-21 16:39
Met same issue. It looks like the bug from websocket-client. I don't know why the latest version of pysher need requirements = ["websocket-client<=0.48"]. I had compare the 0.48 with the latest version of websocket-client at _app.py(start from line 155, function close). In the old version it doesn't set the `self.sock = None` after `self.sock.close(**kwargs)`, but latest websocket-client did(at line 164 in _app.py). Which is the reason WebSocketException raise during reconnect.

So @nlsdfnbch, could you help to update the websocket-client to fix this bug? Thanks.

**Comment by deepbrook** [comment] 2018-08-21 17:36
I currently cannot! But you can! We can't upgrade the websocket version until the `_on_*` methods are made compatible with the new version - since the websocket client doesn't use semantic versioning, the version doesn't show the incompatibility issue with those.

It's a small change, and should be easily resolved. However, I became a dad a few days ago and am otherwise occupied :)

**Comment by xmurobi** [comment] 2018-08-23 15:58
@nlsdfnbch Congratulations!!!

I had submit the merge request to you. Two issues are fixed in this request: 1. Support the latest version of websocket-client. 2. Call reconnect_handler in function _connect_handler.  Could you please help to merge and release a new version? I don't want to build my version on pypi. 

But the underlying reason that cause error 4201 looks like the pysher will miss the pusher:ping when the server flooding the channel with a mass of data. Which cause the pusher server think that the client was died.

**Closed as completed** 2018-08-26 10:43 UTC
Labels: help wanted
