### ISSUE TITLE
Reconnect after connection error 4200 or similar fails

### ISSUE THREAD

**Issue by dustyrock** [nlsdfnbch/Pysher#20] opened 2018-04-27 10:42 UTC
When encountering connection error 4200 or similar, the pysher code obviously tries to re-establish the websocket connection more than once and then fails, see logs below. 

Thereafter no further messages from pusher are received unless the script is restarted manually.
Unfortunately this is really bad for my use case.

I have tried setting the flag self.needs_reconnect to False in the function "def _connect(self)" before the while statement, but then encountered other issues.
Any hints how to make reconnect after connection errors work automatically?

Log messages:
============

Connection: Received error 4200
close status: 4200
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/pysher/connection.py", line 94, in run
    self._connect()
  File "/usr/local/lib/python3.5/dist-packages/pysher/connection.py", line 118, in _connect
    self.socket.run_forever(**self.socket_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_app.py", line 203, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened

**Comment by caliloo** [comment] 2018-08-24 21:55
I've experienced this problem too. My hunch is that pysher does close itself down upon receiving this, but not the websocket. So when pysher comes around and tries to reconnect, it ends up with a websocket already open ...

I've not looked in the code yet to see where this can be fixed. I'll be looking into it over the next month, unless someone beats me to it (that 'd be welcome :) ) A good starting point would probably be to try and reproduce the issue via the test scaffolding (and fixing that at the same time ...).

**Comment by caliloo** [comment] 2018-08-24 22:00
actually it looks like the PR for issue #18 can probably fix this

**Comment by deepbrook** [comment] 2018-08-26 11:00
This should be taken care of in pysher-1.0.0!

**Closed as completed by deepbrook** 2018-08-26 11:00 UTC
Labels: bug, help wanted
